version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  fileservice:
    container_name: file
    build:
      context: .
      dockerfile: ../microservices/mapMicroService/micro-service-map/Dockerfile
    env_file:
      - ../microservices/mapMicroService/micro-service-map/.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: